from pathlib import Path
p=Path('tk2/tasten.html')
s=p.read_text(encoding='utf-8')

nav_old='''          <button class="header-nav-btn" data-view="train"><span class="header-nav-ico">◎</span><span>Challenge</span></button>\n          <button class="header-nav-btn" data-view="memory"><span class="header-nav-ico">▦</span><span>Memory</span></button>'''
nav_new='''          <button class="header-nav-btn" data-view="train"><span class="header-nav-ico">◎</span><span>Challenge</span></button>\n          <button class="header-nav-btn" data-view="hunt"><span class="header-nav-ico">⌕</span><span>Fehlerjagd</span></button>\n          <button class="header-nav-btn" data-view="memory"><span class="header-nav-ico">▦</span><span>Memory</span></button>'''
assert nav_old in s, 'nav anchor missing'
s=s.replace(nav_old,nav_new,1)

memory_anchor='''      <section class="view" id="view-memory">'''
hunt_html='''      <section class="view" id="view-hunt">\n        <div class="view-inner">\n          <div class="view-head">\n            <div><span class="eyebrow">10 Runden · genau ein Fehler</span><h1>Fehlerjagd</h1><p>Vier Zuordnungen – eine davon ist falsch. Finde sie.</p></div>\n            <span class="count-pill" id="huntRound">1 / 10</span>\n          </div>\n          <div class="practice-layout">\n            <div class="practice-card hunt-stage">\n              <span class="prompt-label">Welche Zuordnung stimmt nicht?</span>\n              <div class="hunt-options" id="huntOptions"></div>\n              <div class="hunt-feedback" id="huntFeedback"></div>\n              <div class="practice-actions"><button class="solid-btn" id="huntNext" hidden>Weiter →</button></div>\n            </div>\n            <aside class="side-card">\n              <div><h3>Fehlerjagd</h3><select class="mode-select" id="huntCategory" aria-label="Fehlerjagd-Kategorie"></select><p style="color:var(--muted);font-size:.86rem;line-height:1.45;margin:10px 0 12px">Bis zu vier Zuordnungen pro Runde. Genau eine Kombination gehört nicht zur Bedeutung.</p><button class="soft-btn" id="huntRestart">Neue Fehlerjagd</button></div>\n              <div class="mini-stats">\n                <div class="mini-stat"><span>Punkte</span><strong id="huntScore">0 / 1000</strong></div>\n                <div class="mini-stat"><span>Gefunden</span><strong id="huntCaught">0 / 10</strong></div>\n                <div class="mini-stat"><span>Serie</span><strong id="huntStreak">0</strong></div>\n                <div class="mini-stat"><span>Fehlklicks</span><strong id="huntMisses">0</strong></div>\n              </div>\n            </aside>\n          </div>\n        </div>\n      </section>\n\n'''
assert memory_anchor in s, 'memory view anchor missing'
s=s.replace(memory_anchor,hunt_html+memory_anchor,1)

css='''\n/* --- Fehlerjagd ---------------------------------------------------------- */\n.hunt-stage{justify-content:flex-start;padding-top:clamp(24px,4vw,38px)}\n.hunt-stage .prompt-label{margin-bottom:18px}\n.hunt-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;width:min(820px,100%)}\n.hunt-option{position:relative;min-height:150px;border:1px solid var(--line);border-radius:20px;background:color-mix(in srgb,var(--panel) 90%,var(--panel2));padding:18px;cursor:pointer;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;gap:15px;text-align:left;box-shadow:0 8px 24px rgba(15,23,42,.06);transition:.18s ease;-webkit-tap-highlight-color:transparent}\n.hunt-option:hover:not(:disabled){transform:translateY(-2px);border-color:color-mix(in srgb,var(--blue) 42%,var(--line));box-shadow:0 13px 30px rgba(15,23,42,.1)}\n.hunt-option strong{font-size:1rem;line-height:1.3;padding-right:28px}\n.hunt-option .challenge-keyset{justify-content:flex-start}\n.hunt-option.false-alarm{border-color:#ef4444;background:color-mix(in srgb,#ef4444 7%,var(--panel));animation:challengeWrong .38s ease}\n.hunt-option.false-alarm:after{content:'✓ Diese stimmt';position:absolute;right:12px;top:10px;font-size:.69rem;font-weight:900;color:#dc2626}\n.hunt-option.caught{border-color:#10b981;background:color-mix(in srgb,#10b981 8%,var(--panel));box-shadow:0 0 0 2px color-mix(in srgb,#10b981 35%,transparent),0 13px 30px rgba(16,185,129,.15)}\n.hunt-option.caught .challenge-key{--key-bottom:#059669;border-color:#34d399;border-bottom-color:#059669;background:linear-gradient(180deg,#ecfdf5 0%,#d1fae5 60%,#a7f3d0 100%);color:#065f46}\nhtml[data-theme="dark"] .hunt-option.caught .challenge-key{--key-bottom:#064e3b;background:linear-gradient(180deg,#047857,#065f46);color:#ecfdf5}\n.hunt-feedback{display:none;width:min(820px,100%);margin-top:16px;padding:14px 16px;border:1px solid color-mix(in srgb,var(--green) 40%,var(--line));border-radius:16px;background:color-mix(in srgb,var(--green) 7%,var(--panel));text-align:left}\n.hunt-feedback.show{display:block}.hunt-feedback strong{display:block;margin-bottom:8px}.hunt-feedback .challenge-keyset{justify-content:flex-start}.hunt-feedback p{margin:10px 0 0;color:var(--muted);font-size:.86rem}\n@media(max-width:760px){.hunt-options{grid-template-columns:1fr}.hunt-option{min-height:128px;padding:15px}.hunt-stage{padding:22px 14px}}\n'''
assert '</style>' in s
s=s.replace('</style>',css+'\n</style>',1)

s=s.replace("const titles={home:'Shortcut Lab',learn:'Alle Tastenkürzel',train:'Challenge',memory:'Memory',favorites:'Favoriten'};","const titles={home:'Shortcut Lab',learn:'Alle Tastenkürzel',train:'Challenge',hunt:'Fehlerjagd',memory:'Memory',favorites:'Favoriten'};",1)
s=s.replace("['memoryCategory','challengeCategory']","['memoryCategory','challengeCategory','huntCategory']",1)

js_anchor='''const MEMORY_DIFFS={easy:{label:'Einfach',pairs:4,max:80,exp:.30},medium:{label:'Mittel',pairs:8,max:120,exp:.45},hard:{label:'Schwer',pairs:10,max:140,exp:.55},ultra:{label:'Ultra',pairs:12,max:160,exp:.65}};'''
hunt_js=r'''const hunt={round:0,total:10,score:0,caught:0,streak:0,misses:0,roundMisses:0,solved:false,target:null,rows:[]};
function huntPool(){const s=$('#huntCategory');return poolForCategory(s?s.value:'all')}
function updateHuntHUD(){$('#huntRound').textContent=hunt.round>=hunt.total?'Geschafft ✓':`${hunt.round+1} / ${hunt.total}`;$('#huntScore').textContent=`${hunt.score} / ${hunt.total*100}`;$('#huntCaught').textContent=`${hunt.caught} / ${hunt.total}`;$('#huntStreak').textContent=hunt.streak;$('#huntMisses').textContent=hunt.misses}
function huntWrongShortcut(item,selected){const used=new Set(selected.map(x=>x.id));let candidates=huntPool().filter(x=>x.id!==item.id&&!used.has(x.id));if(!candidates.length)candidates=shortcuts.filter(x=>x.id!==item.id&&!used.has(x.id));if(!candidates.length)candidates=shortcuts.filter(x=>x.id!==item.id);return shuffleArray(candidates.slice())[0]||item}
function startHunt(){Object.assign(hunt,{round:0,total:10,score:0,caught:0,streak:0,misses:0,roundMisses:0,solved:false,target:null,rows:[]});renderHunt()}
function renderHunt(){if(hunt.round>=hunt.total){finishHunt();return}hunt.solved=false;hunt.roundMisses=0;const pool=huntPool();if(pool.length<2){$('#huntOptions').innerHTML='<div class="empty" style="display:block;grid-column:1/-1">Für die Fehlerjagd braucht es mindestens zwei Kürzel.</div>';$('#huntFeedback').classList.remove('show');$('#huntNext').hidden=true;updateHuntHUD();return}const count=Math.min(4,pool.length),selected=shuffleArray(pool.slice()).slice(0,count),targetIndex=Math.floor(Math.random()*count);hunt.rows=selected.map((item,i)=>({item,shown:i===targetIndex?huntWrongShortcut(item,selected):item,isTarget:i===targetIndex,missed:false}));hunt.target=hunt.rows[targetIndex];const host=$('#huntOptions');host.innerHTML='';hunt.rows.forEach((row,i)=>{const b=document.createElement('button');b.type='button';b.className='hunt-option';b.dataset.index=i;b.innerHTML=`<strong>${escapeHtml(row.item.title)}</strong>${challengeKeyMarkup(row.shown)}`;b.onclick=()=>gradeHunt(b,i);host.appendChild(b)});$('#huntFeedback').classList.remove('show');$('#huntFeedback').innerHTML='';$('#huntNext').hidden=true;updateHuntHUD()}
function gradeHunt(btn,index){if(hunt.solved)return;const row=hunt.rows[index];if(!row)return;if(!row.isTarget){if(row.missed)return;row.missed=true;hunt.misses++;hunt.roundMisses++;hunt.streak=0;btn.classList.add('false-alarm');haptic([18,28,18]);toast('Diese Zuordnung stimmt');updateHuntHUD();return}hunt.solved=true;hunt.caught++;hunt.streak++;hunt.score+=Math.max(40,100-hunt.roundMisses*20);btn.classList.add('caught');$$('.hunt-option').forEach(b=>b.disabled=true);const f=$('#huntFeedback');f.innerHTML=`<strong>Fehler gefunden ✓</strong><div>${escapeHtml(row.item.title)} gehört zu:</div><div style="margin-top:10px">${challengeKeyMarkup(row.item)}</div><p>Gezeigt wurde fälschlicherweise ${escapeHtml(keyText(row.shown))}.</p>`;f.classList.add('show');$('#huntNext').hidden=false;haptic([15,25,20]);updateHuntHUD()}
function nextHunt(){if(!hunt.solved)return;hunt.round++;renderHunt()}
function finishHunt(){$('#huntOptions').innerHTML='';$('#huntFeedback').innerHTML=`<strong>Fehlerjagd abgeschlossen 🎯</strong><p>${hunt.caught} von ${hunt.total} Fehlern gefunden · ${hunt.misses} Fehlklick${hunt.misses===1?'':'s'} · ${hunt.score} Punkte.</p>`;$('#huntFeedback').classList.add('show');$('#huntNext').hidden=true;hunt.round=hunt.total;updateHuntHUD();haptic([20,35,20,35,50])}
'''
assert js_anchor in s, 'memory js anchor missing'
s=s.replace(js_anchor,hunt_js+'\n'+js_anchor,1)

listener_old="$('#challengeNext').onclick=nextChallenge;$('#challengeRestart').onclick=()=>startChallenge();$('#challengeCategory').onchange=()=>startChallenge();"
listener_new=listener_old+"\n$('#huntNext').onclick=nextHunt;$('#huntRestart').onclick=startHunt;$('#huntCategory').onchange=startHunt;"
assert listener_old in s, 'listener anchor missing'
s=s.replace(listener_old,listener_new,1)

startup_old='renderHome();renderLearn();fillMemoryCategories();startChallenge();renderFavorites();updateFavoriteUI();'
startup_new='renderHome();renderLearn();fillMemoryCategories();startChallenge();startHunt();renderFavorites();updateFavoriteUI();'
assert startup_old in s, 'startup anchor missing'
s=s.replace(startup_old,startup_new,1)

for marker in ['data-view="hunt"','id="view-hunt"','id="huntCategory"','function startHunt()','function gradeHunt','huntCategory\'']:
    pass
p.write_text(s,encoding='utf-8')
print('patched Fehlerjagd')
