from pathlib import Path

p=Path('hw/A13.html')
s=p.read_text(encoding='utf-8')

old='''  <div class="grid grid-cols-2 sm:grid-cols-5 gap-2">
    <div class="rounded-xl border border-amber-200 dark:border-amber-900/60 bg-amber-50/70 dark:bg-amber-950/20 p-3 text-center"><i class="fa-solid fa-mountain text-amber-600 text-lg"></i><div class="text-xs font-black mt-1">1 · Rohstoffe</div><div class="text-[10px] text-slate-500 mt-1">Metalle & kritische Rohstoffe</div></div>
    <div class="rounded-xl border border-violet-200 dark:border-violet-900/60 bg-violet-50/70 dark:bg-violet-950/20 p-3 text-center"><i class="fa-solid fa-industry text-violet-600 text-lg"></i><div class="text-xs font-black mt-1">2 · Herstellung</div><div class="text-[10px] text-slate-500 mt-1">Energie, Wasser, CO₂-Rucksack</div></div>
    <div class="rounded-xl border border-sky-200 dark:border-sky-900/60 bg-sky-50/70 dark:bg-sky-950/20 p-3 text-center"><i class="fa-solid fa-laptop text-sky-600 text-lg"></i><div class="text-xs font-black mt-1">3 · Nutzung</div><div class="text-[10px] text-slate-500 mt-1">Strom, Cloud & KI</div></div>
    <div class="rounded-xl border border-emerald-200 dark:border-emerald-900/60 bg-emerald-50/70 dark:bg-emerald-950/20 p-3 text-center"><i class="fa-solid fa-screwdriver-wrench text-emerald-600 text-lg"></i><div class="text-xs font-black mt-1">4 · Weiter nutzen</div><div class="text-[10px] text-slate-500 mt-1">Reparieren, aufrüsten, refurbished</div></div>
    <div class="rounded-xl border border-teal-200 dark:border-teal-900/60 bg-teal-50/70 dark:bg-teal-950/20 p-3 text-center col-span-2 sm:col-span-1"><i class="fa-solid fa-recycle text-teal-600 text-lg"></i><div class="text-xs font-black mt-1">5 · Recycling</div><div class="text-[10px] text-slate-500 mt-1">Urban Mining & Rückgewinnung</div></div>
  </div>'''
new='''  <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2">
    <div class="rounded-xl border border-amber-200 dark:border-amber-900/60 bg-amber-50/70 dark:bg-amber-950/20 p-3 text-center"><i class="fa-solid fa-mountain text-amber-600 text-lg"></i><div class="text-xs font-black mt-1">1 · Rohstoffe</div><div class="text-[10px] text-slate-500 mt-1">Kobalt, Lithium, Gold & Konflikte</div></div>
    <div class="rounded-xl border border-violet-200 dark:border-violet-900/60 bg-violet-50/70 dark:bg-violet-950/20 p-3 text-center"><i class="fa-solid fa-industry text-violet-600 text-lg"></i><div class="text-xs font-black mt-1">2 · Herstellung</div><div class="text-[10px] text-slate-500 mt-1">Energie, Wasser & CO₂-Rucksack</div></div>
    <div class="rounded-xl border border-blue-200 dark:border-blue-900/60 bg-blue-50/70 dark:bg-blue-950/20 p-3 text-center"><i class="fa-solid fa-ship text-blue-600 text-lg"></i><div class="text-xs font-black mt-1">3 · Transport</div><div class="text-[10px] text-slate-500 mt-1">Schiff, Luftfracht & Handel</div></div>
    <div class="rounded-xl border border-sky-200 dark:border-sky-900/60 bg-sky-50/70 dark:bg-sky-950/20 p-3 text-center"><i class="fa-solid fa-laptop text-sky-600 text-lg"></i><div class="text-xs font-black mt-1">4 · Nutzung</div><div class="text-[10px] text-slate-500 mt-1">Strom, Standby, Cloud & KI</div></div>
    <div class="rounded-xl border border-emerald-200 dark:border-emerald-900/60 bg-emerald-50/70 dark:bg-emerald-950/20 p-3 text-center"><i class="fa-solid fa-screwdriver-wrench text-emerald-600 text-lg"></i><div class="text-xs font-black mt-1">5 · Länger nutzen</div><div class="text-[10px] text-slate-500 mt-1">Reparieren, aufrüsten, refurbished</div></div>
    <div class="rounded-xl border border-teal-200 dark:border-teal-900/60 bg-teal-50/70 dark:bg-teal-950/20 p-3 text-center"><i class="fa-solid fa-recycle text-teal-600 text-lg"></i><div class="text-xs font-black mt-1">6 · Recycling</div><div class="text-[10px] text-slate-500 mt-1">Urban Mining & Rückgewinnung</div></div>
  </div>'''
assert old in s, 'lifecycle grid not found'
s=s.replace(old,new,1)
s=s.replace('Green IT betrachtet nicht nur den Stromverbrauch. Auch Rohstoffabbau, Herstellung, Nutzungsdauer, Reparatur, Wiederverwendung und Recycling gehören dazu.','Green IT betrachtet den ganzen Weg eines Geräts: Rohstoffabbau, Herstellung, Transport und Handel, Nutzung, längere Nutzung durch Reparatur/Wiederverwendung sowie Recycling.',1)

repls={
"{id:'sleep',title:'Du gehst in die Mittagspause',text:'Der PC wird für etwa eine Stunde nicht gebraucht.',correct:'sleepmode',why:'Energiespar- oder Ruhezustand senkt den Stromverbrauch während längerer Pausen.',options:[{id:'leave',icon:'fa-sun',title:'Bildschirm und PC laufen lassen',sub:'Alles bleibt unverändert an'},{id:'sleepmode',icon:'fa-moon',title:'Energiesparmodus nutzen',sub:'Bei längerer Pause Energie sparen'},{id:'video',icon:'fa-play',title:'Ein Video laufen lassen',sub:'Damit der PC nicht einschläft'}]}":
"{id:'sleep',title:'Der Schul-PC wird länger nicht gebraucht',text:'Mittagspause, Nacht oder Wochenende: Der Computer steht lange ungenutzt da.',correct:'sleepmode',why:'Bei Pausen hilft der Energiesparmodus. Über Nacht oder längere Zeit kann vollständiges Ausschalten bzw. eine schaltbare Steckdosenleiste unnötigen Standby-Verbrauch vermeiden.',options:[{id:'leave',icon:'fa-sun',title:'Einfach weiterlaufen lassen',sub:'Auch nachts und am Wochenende'},{id:'sleepmode',icon:'fa-power-off',title:'Energiesparen oder ganz ausschalten',sub:'Passend zur Dauer der Pause'},{id:'video',icon:'fa-play',title:'Ein Video laufen lassen',sub:'Damit der PC nicht einschläft'}]}",
"{id:'ewaste',title:'Ein altes Tablet ist kaputt',text:'Es lässt sich nicht mehr sinnvoll reparieren. Im Gerät stecken Metalle, Glas und Elektronik.',correct:'recycle',why:'Elektrogeräte gehören in die Rückgabe- oder Sammelstelle. Beim Urban Mining können Metalle und andere Wertstoffe aus Altgeräten zurückgewonnen werden.',options:[{id:'trash',icon:'fa-trash-can',title:'In den Hausmüll werfen',sub:'Zusammen mit normalem Abfall'},{id:'recycle',icon:'fa-recycle',title:'Zur Sammelstelle bringen',sub:'Elektroschrott korrekt zurückgeben'},{id:'street',icon:'fa-road',title:'Neben den Container stellen',sub:'Irgendjemand nimmt es vielleicht'}]}":
"{id:'ewaste',title:'Ein altes Tablet ist kaputt',text:'Es lässt sich nicht mehr sinnvoll reparieren. Im Gerät stecken Kupfer, Gold, Silber, Kunststoffe, Glas und weitere Materialien.',correct:'recycle',why:'Beim Urban Mining können wertvolle Metalle zurückgewonnen werden. Nicht alle Kunststoffe und Klebstoffe lassen sich vollständig recyceln – deshalb ist korrekte Rückgabe wichtig.',options:[{id:'trash',icon:'fa-trash-can',title:'In den Hausmüll werfen',sub:'Wertstoffe gehen dem Recycling verloren'},{id:'recycle',icon:'fa-recycle',title:'Zur Sammelstelle bringen',sub:'Elektroschrott korrekt zurückgeben'},{id:'street',icon:'fa-road',title:'Neben den Container stellen',sub:'Keine geregelte Rückgewinnung'}]}",
"{id:'buy',title:'Du brauchst einen Laptop für die Schule',text:'Office, Browser und Videokonferenzen sind wichtig. High-End-Gaming brauchst du nicht.',correct:'fit',why:'Nachhaltige IT-Beschaffung bedeutet: passend dimensionieren, lange Nutzungsdauer, Reparierbarkeit und ausreichende Software-Unterstützung statt unnötiger High-End-Hardware.',options:[{id:'max',icon:'fa-bolt',title:'Maximal ausgestattetes Gaming-Gerät',sub:'Mehr Leistung als benötigt'},{id:'fit',icon:'fa-laptop',title:'Passendes, langlebiges Modell',sub:'Genug Leistung + gute Reparierbarkeit'},{id:'yearly',icon:'fa-calendar',title:'Jedes Jahr ein günstiges neues',sub:'Regelmässig ersetzen'}]}":
"{id:'buy',title:'Eine Schule beschafft 30 neue Laptops',text:'Die Geräte sollen mehrere Jahre für Office, Browser und Videokonferenzen reichen. High-End-Gaming ist nicht nötig.',correct:'fit',why:'Grüne IT-Beschaffung achtet auf passende Leistung, lange Software-Unterstützung, Reparierbarkeit bzw. austauschbare Teile, Refurbished-Optionen und glaubwürdige Nachhaltigkeitskriterien/Siegel.',options:[{id:'max',icon:'fa-bolt',title:'30 High-End-Gaming-Geräte',sub:'Mehr Leistung und Ressourcen als nötig'},{id:'fit',icon:'fa-laptop',title:'Langlebig & reparierbar beschaffen',sub:'Passende Leistung, Support, Refurbished prüfen'},{id:'yearly',icon:'fa-calendar',title:'Das billigste Wegwerfmodell',sub:'Kurze Lebensdauer in Kauf nehmen'}]}",
"{id:'lifecycle',artId:'updates',title:'Nur der Stromverbrauch zählt?',text:'Du willst beurteilen, wie nachhaltig ein Smartphone ist. Jemand schaut nur darauf, wie viel Strom es beim Laden braucht.',correct:'whole',why:'Zur Umweltwirkung gehört der ganze Lebenszyklus: Rohstoffe, Herstellung, Nutzung, Reparatur/Wiederverwendung und Recycling.',options:[{id:'charge',icon:'fa-plug-circle-bolt',title:'Nur das Laden betrachten',sub:'Herstellung und Entsorgung ignorieren'},{id:'whole',icon:'fa-arrows-spin',title:'Den ganzen Lebenszyklus betrachten',sub:'Von Rohstoffen bis Recycling'},{id:'price',icon:'fa-tag',title:'Nur auf den Kaufpreis schauen',sub:'Ökologische Folgen ausblenden'}]}":
"{id:'lifecycle',artId:'updates',title:'Nur der Stromverbrauch zählt?',text:'Du willst beurteilen, wie nachhaltig ein Smartphone ist. Jemand schaut nur darauf, wie viel Strom es beim Laden braucht.',correct:'whole',why:'Zur Umweltwirkung gehört der ganze Lebenszyklus: Rohstoffe, Herstellung, Transport/Handel, Nutzung, Reparatur/Wiederverwendung und Recycling.',options:[{id:'charge',icon:'fa-plug-circle-bolt',title:'Nur das Laden betrachten',sub:'Herstellung, Transport und Entsorgung ignorieren'},{id:'whole',icon:'fa-arrows-spin',title:'Den ganzen Lebenszyklus betrachten',sub:'Von Rohstoffen bis Urban Mining'},{id:'price',icon:'fa-tag',title:'Nur auf den Kaufpreis schauen',sub:'Ökologische Folgen ausblenden'}]}",
"{id:'rawmaterials',artId:'ewaste',title:'Im Smartphone stecken wertvolle Rohstoffe',text:'Gold, Kupfer, Lithium, Kobalt und weitere Rohstoffe müssen gewonnen und verarbeitet werden. Einige gelten als kritisch und ihre Gewinnung kann Menschen und Umwelt belasten.',correct:'responsible',why:'Lange Nutzung, Reparierbarkeit, verantwortungsvollere Lieferketten und korrektes Recycling verringern den Druck auf neue Rohstoffe.',options:[{id:'replace',icon:'fa-mobile-screen-button',title:'Möglichst oft ersetzen',sub:'Damit immer das neueste Modell da ist'},{id:'responsible',icon:'fa-earth-europe',title:'Lange nutzen + verantwortungsvoll beschaffen',sub:'Reparierbarkeit, Lieferkette und Recycling mitdenken'},{id:'drawer',icon:'fa-box-archive',title:'Altgeräte einfach sammeln',sub:'Wertstoffe bleiben ungenutzt in der Schublade'}]}":
"{id:'rawmaterials',artId:'ewaste',title:'Kobalt, Lithium und Gold haben eine Vorgeschichte',text:'Kobalt kann mit schwierigen Arbeits- und Schutzbedingungen im Bergbau verbunden sein, Lithiumgewinnung in trockenen Regionen mit hohem Wasserbedarf und Goldgewinnung mit problematischen Chemikalien.',correct:'responsible',why:'Nachhaltige Lieferketten sind gemeinsame Verantwortung: Hersteller und Handel, Gesetzgeber sowie Konsumentinnen und Konsumenten können durch Beschaffung, Regeln, längere Nutzung und Recycling Einfluss nehmen.',options:[{id:'replace',icon:'fa-mobile-screen-button',title:'Möglichst oft ersetzen',sub:'Mehr Nachfrage nach neuen Rohstoffen erzeugen'},{id:'responsible',icon:'fa-earth-europe',title:'Lieferkette + lange Nutzung mitdenken',sub:'Hersteller, Politik und Konsum tragen Verantwortung'},{id:'drawer',icon:'fa-box-archive',title:'Altgeräte einfach sammeln',sub:'Wertstoffe bleiben ungenutzt in der Schublade'}]}",
"{id:'backpack',artId:'buy',title:'Der ökologische Rucksack entsteht früh',text:'Ein funktionierendes Gerät soll ersetzt werden, obwohl es alle Aufgaben noch erfüllt. Bei der Herstellung wurden bereits Rohstoffe, Wasser und viel Energie eingesetzt.',correct:'longer',why:'Je länger ein geeignetes Gerät genutzt wird, desto länger verteilt sich der Herstellungsaufwand auf seine Nutzungszeit.',options:[{id:'yearly',icon:'fa-calendar-xmark',title:'Jährlich neu kaufen',sub:'Auch ohne technischen Grund'},{id:'longer',icon:'fa-hourglass-half',title:'Das Gerät länger nutzen',sub:'Herstellungsaufwand besser ausnutzen'},{id:'spare',icon:'fa-boxes-stacked',title:'Neues kaufen und altes lagern',sub:'Zwei Geräte besitzen, aber nur eines nutzen'}]}":
"{id:'backpack',artId:'buy',title:'Der ökologische Rucksack entsteht früh',text:'Noch bevor ein Gerät eingeschaltet wird, wurden Rohstoffe abgebaut, Bauteile mit viel Energie und Wasser hergestellt und über weite Wege transportiert.',correct:'longer',why:'Bei vielen IT-Geräten ist die Herstellung ein grosser Teil der Umweltbelastung. Wird ein geeignetes Gerät z. B. vier statt zwei Jahre genutzt, verteilt sich dieser Herstellungsaufwand auf deutlich mehr Nutzungsjahre.',options:[{id:'yearly',icon:'fa-calendar-xmark',title:'Jährlich neu kaufen',sub:'Den Herstellungsrucksack ständig neu auslösen'},{id:'longer',icon:'fa-hourglass-half',title:'Das Gerät länger nutzen',sub:'Herstellungsaufwand besser ausnutzen'},{id:'spare',icon:'fa-boxes-stacked',title:'Neues kaufen und altes lagern',sub:'Produktion ohne zusätzliche Nutzung'}]}",
"{id:'datacenter',artId:'cloud',title:'Cloud und KI laufen nicht „in der Luft“',text:'Eine Klasse startet aus Spass immer wieder grosse KI-Aufgaben und lässt unnötige Cloud-Jobs weiterlaufen. Dahinter arbeiten Rechenzentren mit Servern, Kühlung und Stromversorgung.',correct:'purposeful',why:'Cloud- und KI-Dienste benötigen reale Rechenleistung in Rechenzentren. Sinnvolle Nutzung und unnötige Jobs vermeiden spart Ressourcen, ohne digitale Dienste grundsätzlich abzulehnen.',options:[{id:'endless',icon:'fa-repeat',title:'Alles beliebig oft wiederholen',sub:'Rechenaufwand spielt keine Rolle'},{id:'purposeful',icon:'fa-server',title:'Dienste gezielt und sinnvoll nutzen',sub:'Unnötige Berechnungen und Jobs vermeiden'},{id:'offline',icon:'fa-ban',title:'Cloud und KI komplett verbieten',sub:'Nur so sei Green IT möglich'}]}":
"{id:'datacenter',artId:'cloud',title:'Cloud und KI laufen nicht „in der Luft“',text:'Websuche, Text-KI und Bildgenerierung wirken ähnlich bequem, benötigen aber unterschiedlich viel Rechenarbeit. Dahinter stehen Rechenzentren mit Servern und Kühlung.',correct:'purposeful',why:'Generative KI berechnet mit grossen Modellen und oft GPU-Clustern viele Rechenschritte; Bildgenerierung kann besonders rechenintensiv sein. Deshalb ist eine KI-Anfrage typischerweise aufwendiger als eine einfache Websuche.',options:[{id:'endless',icon:'fa-repeat',title:'Alles beliebig oft wiederholen',sub:'Rechenaufwand spielt keine Rolle'},{id:'purposeful',icon:'fa-server',title:'Cloud & KI gezielt nutzen',sub:'Unnötige Berechnungen und Wiederholungen vermeiden'},{id:'offline',icon:'fa-ban',title:'Cloud und KI komplett verbieten',sub:'Digitale Dienste sind grundsätzlich schlecht'}]}
}
for a,b in repls.items():
    assert a in s, 'scenario not found: '+a[:40]
    s=s.replace(a,b,1)

p.write_text(s,encoding='utf-8')
print('A13 final theme audit applied')